apiVersion: v1
kind: Secret
metadata:
  name: prometheus-additional-scrapes
  namespace: monitoring
type: Opaque
stringData:
  additional-scrape-configs.yaml: |
    - job_name: external-node-exporters
      scrape_interval: 30s
      static_configs:
        - targets:
            - "10.0.0.11:9100"
            - "10.0.0.12:9100"
            - "10.0.0.13:9100"
          labels:
            role: vm
    - job_name: external-apps
      metrics_path: /metrics
      scrape_interval: 30s
      static_configs:
        - targets:
            - "10.0.0.11:8080"
            - "10.0.0.12:8080"
            - "10.0.0.13:8080"
          labels:
            role: app
