apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: sample-node-app
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: sample-node-app
  namespaceSelector:
    matchNames:
      - default
  podMetricsEndpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s
