apiVersion: v2
name: grafana-platform
description: Wrapper chart for Grafana
type: application
version: 0.1.0
appVersion: "10.5.15"
dependencies:
  - name: grafana
    version: 10.5.15
    repository: https://grafana-community.github.io/helm-charts
